name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v2
        with:
          name: ChillysonSmp
          path: target/*.jar
